//QUESTIONS

export const FETCH_QUESTIONS_BEGIN = 'FETCH_QUESTIONS_BEGIN';
export const FETCH_QUESTIONS_FAIL = 'FETCH_QUESTIONS_FAIL';
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';

export const UPDATE_QUESTION = 'UPDATE_QUESTION';

export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

//INTERFACE

export const STARTGAME = 'STARTGAME';